default_install_hook_types = ["commit-msg"]

[[repos]]
repo = "https://github.com/alessandrojcm/commitlint-pre-commit-hook"
rev = "v9.24.0"
hooks = [
	{ id = "commitlint", name = "commitlint", stages = [
		"commit-msg",
	], language = "node", additional_dependencies = [
		"@commitlint/config-conventional",
	] },
]

[[repos]]
repo = "builtin"
hooks = [{ id = "check-toml" }, { id = "check-json" }, { id = "check-yaml" }]
