services:
  plex:
    image: plexinc/pms-docker:1.43.1.10611-1e34174b1
    container_name: plex
    user: "${UID}:${GID}"
    network_mode: host
    volumes:
      - "${APPDATA_ROOT}/plex/PlexMediaServer:/config"
      - "${APPDATA_ROOT}/plex/transcode:/transcode"
      - "${MEDIA_ROOT}:/data"
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
      - TZ=${TZ}
    restart: unless-stopped
