services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.17
    container_name: sonarr
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - "TZ=${TZ}"
    volumes:
      - "${APPDATA_ROOT}/arr_stack/sonarr/config:/config"
      - "${DOWNLOAD_ROOT}:/downloads"
      - "${MEDIA_ROOT}:/Media"
    ports:
      - "${SONARR_PORT}:8989"
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:6.1.1
    container_name: radarr
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - "TZ=${TZ}"
    volumes:
      - "${APPDATA_ROOT}/arr_stack/radarr/config:/config"
      - "${DOWNLOAD_ROOT}:/downloads"
      - "${MEDIA_ROOT}:/Media"
    ports:
      - "${RADARR_PORT}:7878"
    restart: unless-stopped
  radarr4k:
    image: lscr.io/linuxserver/radarr:6.1.1
    container_name: radarr4k
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - "TZ=${TZ}"
    volumes:
      - "${APPDATA_ROOT}/arr_stack/radarr4k/config:/config"
      - "${DOWNLOAD_ROOT}:/downloads"
      - "${MEDIA_ROOT}:/Media"
    ports:
      - "${RADARR4k_PORT}:7878"
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.5
    container_name: prowlarr
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - "TZ=${TZ}"
    volumes:
      - "${APPDATA_ROOT}/arr_stack/prowlarr/config:/config"
    ports:
      - "${PROWLARR_PORT}:9696"
    restart: unless-stopped
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.2.0
    container_name: seerr
    user: "${UID}:${GID}"
    environment:
      - "TZ=${TZ}"
    volumes:
      - "${APPDATA_ROOT}/arr_stack/seerr/config:/app/config"
    ports:
      - "${SEERR_PORT}:5055"
    restart: unless-stopped
  tautulli:
    image: ghcr.io/tautulli/tautulli:v2.17.1
    container_name: tautulli
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - "TZ=${TZ}"
    ports:
      - "${TAUTULLI_PORT}:8181"
    volumes:
      - "${APPDATA_ROOT}/arr_stack/tautulli/config:/config"
    restart: unless-stopped
  requestrr:
    image: thomst08/requestrr:v2.1.9
    container_name: requestrr
    user: "${UID}:${GID}"
    environment:
      - "TZ=${TZ}"
    ports:
      - "${REQUESTRR_PORT}:4545"
    volumes:
      - "${APPDATA_ROOT}/arr_stack/requestrr/config:/root/config"
    restart: unless-stopped
  profilarr:
    image: santiagosayshey/profilarr:v1.1.4
    container_name: profilarr
    user: "${UID}:${GID}"
    ports:
      - "${PROFILARR_PORT}:6868"
    volumes:
      - "${APPDATA_ROOT}/arr_stack/profilarr/config:/config"
    environment:
      - "TZ=${TZ}"
    restart: unless-stopped
  umlautadaptarr:
    image: pcjones/umlautadaptarr:0.7.5
    container_name: umlautadaptarr
    user: "${UID}:${GID}"
    ports:
      - "${UMLAUTADAPTARR_PORT}:5006"
    environment:
      - "TZ=${TZ}"
      - "SONARR__ENABLED=true"
      - "SONARR__HOST=${HOST}:${SONARR_PORT}"
      - "SONARR__APIKEY=${SONARR_API_KEY}"
      - "RADARR__0__ENABLED=true"
      - "RADARR__0__HOST=${HOST}:${RADARR_PORT}"
      - "RADARR__0__APIKEY=${RADARR_API_KEY}"
      - "RADARR__1__ENABLED=true"
      - "RADARR__1__HOST=${HOST}:${RADARR4k_PORT}"
      - "RADARR__1__APIKEY=${RADARR4k_API_KEY}"
    restart: unless-stopped
  # huntarr:
  #   image: huntarr/huntarr:latest
  #   container_name: huntarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Zurich
  #   ports:
  #     - 9705:9705
  #   volumes:
  #     - /docker/appdata/arr_stack/huntarr/config:/config
  #   restart: unless-stopped

  # maintainerr:
  #   image: ghcr.io/jorenn92/maintainerr:latest
  #   container_name: maintainerr
  #   volumes:
  #     - /docker/appdata/arr_stack/maintainerr/config:/opt/data
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Zurich
  #   ports:
  #     - 6246:6246
  #   restart: unless-stopped
  # homepage:
  #   image: ghcr.io/gethomepage/homepage:latest
  #   container_name: homepage
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - /docker/appdata/homepage/config:/app/config # Make sure your local config directory exists
  #     - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
  #   environment:
  #     HOMEPAGE_ALLOWED_HOSTS: 192.168.1.207:3000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
  #   restart: unless-stopped
