services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:5.0.3
    container_name: sabnzbd
    user: "${UID}:${GID}"
    volumes:
      - "${APPDATA_ROOT}/sabnzbd/config:/config"
      - "${INCOMPLETE_DOWNLOAD_ROOT}:/incomplete-downloads"
      - "${MEDIA_ROOT}/complete:/downloads"
    ports:
      - "${SABNZBD_PORT}:8080"
    environment:
      TZ: ${TZ}
    restart: unless-stopped
